apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-tasky-deployment
  namespace: tasky-app
  labels:
    app: eks-tasky-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-tasky-app
  template:
    metadata:
      labels:
        app: eks-tasky-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: tasky
          image: 442426890564.dkr.ecr.us-east-1.amazonaws.com/takehome/tasky:205c72255e15388e7397de80c6d06f36145dcdea
          ports:
            - name: http
              containerPort: 80
          env:
            - name: MONGODB_URI
              value: mongodb+srv://myUserAdmin:lolsauce13@3.93.24.132
            - name: SECRET_KEY
              value: secret123
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux