apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-service-account
  namespace: tasky-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cluster-admin-service-account
    namespace: tasky-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-tasky-deployment
  namespace: tasky-app
  labels:
    app: eks-tasky-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-tasky-app
  template:
    metadata:
      labels:
        app: eks-tasky-app
    spec:
      serviceAccountName: cluster-admin-service-account
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: tasky
          image: 442426890564.dkr.ecr.us-east-1.amazonaws.com/takehome/tasky:8020110e3efaf99729ada28166eb03835e06a990
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: MONGODB_URI
              value: MONGO_URI_VALUE
            - name: SECRET_KEY
              value: secret123
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux