name: Deploy AWS Infrastructure

on: workflow_dispatch

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Scan for misconfigurations
        run: |
          cd terraform 
          terraform init
          terraform plan --out tfplan.binary
          terraform show -json tfplan.binary > tfplan.json
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
          echo "trivy setup"
          trivy -v
          misconfigs=$(trivy config --severity CRITICAL -f json ./tfplan.json | jq -r '.Results[1].Misconfigurations' | jq length)
          echo $misconfigs
          if [ "$misconfigs" -gt 10 ]; then
            echo "::error::Failing due to many Critical infrastructure misconfigurations: misconfigs"
            exit 1
          fi
      - name: Initialise project and view terraform plan
        run: |
          cd terraform 
          terraform fmt
          terraform init 
          terraform apply